name: atletes_sport_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  shared_preferences: ^2.0.8
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^3.5.3
  http: ^0.13.4
  firebase_storage: ^10.0.6
  cached_network_image: ^3.1.0
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  url_launcher: ^6.0.12
  google_sign_in: ^5.0.0-nullsafety
  image_picker: ^0.8.4+4
  permission_handler: ^8.3.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
